name: mulit-env-workflow

on: 
  workflow_dispatch:
    inputs:
      target_env:
        description: 'Choose deployment target'
        type: choice
        required: true
        default: 'development'
        options:
          - dev
          - staging
          - prod

jobs:
  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: checkout code
        uses: actions/checkout@v4

      - name: execute deploymet logic
        run : |
          echo "Deployment to ${{ github.event.inputs.target_env }} completed successfully."




